### ISSUE TITLE
Clarifications on the metrics for data analytics

### ISSUE THREAD

**Issue by PavlovGrigor** [DITAS-Project/data-analytics#3]
We need to clarify what will be the metrics in order to execute data anlytics;
For that issue will be required assistance  from POLIMI;
Due to 29th of April;

**Comment by PavlovGrigor** [comment]
Due to Easter Holidays the deadline is changed until 30th of April

**Comment by bogdan-ds** [comment]
Things look a lot clearer to me now and that's why I refactored the metric API call, anyone following the thread, please review this:

https://github.com/DITAS-Project/data-analytics/blob/master/api/DataAnalyticsAPI.yaml

And let me know if you have any comments.

**Comment by bogdan-ds** [comment]
This has been resolved and the metric calls have been implemented
