### ISSUE TITLE
The development of the metrics API calls

### ISSUE THREAD

**Issue by PavlovGrigor** [DITAS-Project/data-analytics#4]
CloudSigma needs to provide API calls for the execution of Data Analytics;
Due to the next general assembly meeting;

**Comment by bogdan-ds** [comment]
I created a very rough beta of the meter API call that was needed, this is an example query: http://178.22.69.180:8080/data-analytics/meter/tubvdc/?operationID=getBloodTestComponentAverage&name=ramGain&startTime=2019-05-14T10%3A25%3A32&endTime=2019-05-14T13%3A25%3A32
you can change the query parameters to search in the elasticsearch
